function renderHome(){ $('categoryRow').innerHTML=CATEGORIES.map(c=>`<button class="level ${state.category===c.key?'active':''}" onclick="setCategory('${c.key}')">${c.icon} ${c.label}</button>`).join(''); $('petRow').innerHTML=PETS.map((p,i)=>`<button class="pet ${state.pet===i?'active':''}" onclick="setPet(${i})"><div style="font-size:2rem">${p.icon}</div><div>${p.name}</div></button>`).join(''); $('rewardRow').innerHTML=REWARDS.map(r=>`<div class="reward ${state.stars>=r.cost?'':'locked'}"><div style="font-size:2rem">${r.icon}</div><div>${r.name}</div><div style="font-size:.8rem;margin-top:4px">${r.cost} ⭐</div></div>`).join(''); $('albumGrid').innerHTML=STICKERS.map((s,i)=>`<div class="album-item ${i<state.unlockedStickers?'':'locked'}"><div class="icon">${s}</div><div class="name">מדבקה</div></div>`).join(''); $('activeCount').textContent=[...state.enabledIds].length; $('totalCount').textContent=ALL_WORDS.length; $('difficultyLabel').textContent=currentDifficulty(); renderWordList(); }
function setCategory(key){state.category=key; renderHome();}
function setPet(i){state.pet=i; renderHome();}
function setAllWords(on){state.enabledIds.clear(); if(on) ALL_WORDS.forEach(w=>state.enabledIds.add(w.id)); saveSettings(); renderHome();}
function enableByLevel(max){state.enabledIds.clear(); ALL_WORDS.filter(w=>w.level<=max).forEach(w=>state.enabledIds.add(w.id)); saveSettings(); renderHome();}
function renderWordList(){const q=norm(document.getElementById('wordSearch').value); const cat=document.getElementById('settingsCategory').value; const rows=ALL_WORDS.filter(function(w){ return (cat==='all'||w.cat===cat) && (!q || norm(w.en).includes(q) || norm(w.he).includes(q)); }).slice(0,260); document.getElementById('wordList').innerHTML=rows.map(function(w){ const toggleId='wordToggle-'+w.id; return '<label class="word-item" for="'+toggleId+'"><div class="icon">'+w.emoji+'</div><div class="meta"><div class="en">'+w.en+'</div><div class="he">'+w.he+' · קושי '+w.level+(isSimpleWord(w)?' · מילה פשוטה':'')+'</div></div><input id="'+toggleId+'" name="word_toggle_'+w.id+'" class="switch" type="checkbox" '+(state.enabledIds.has(w.id)?'checked':'')+' onchange="toggleWord(\''+w.id+'\', this.checked)"></label>'; }).join('');}
function toggleWord(id, on){ if(on) state.enabledIds.add(id); else state.enabledIds.delete(id); saveSettings(); $('activeCount').textContent=[...state.enabledIds].length; }

function burst(node){ const r=node.getBoundingClientRect(), cx=r.left+r.width/2, cy=r.top+r.height/2; const colors=['#ffd24f','#ff7fcb','#59d7ff','#49e7a3','#fff']; for(let i=0;i<22;i++){ const p=document.createElement('span'); p.className='particle'; const s=6+Math.random()*10; p.style.width=s+'px'; p.style.height=s+'px'; p.style.left=cx+'px'; p.style.top=cy+'px'; p.style.background=pick(colors); p.style.setProperty('--x',`${(Math.random()-.5)*180}px`); p.style.setProperty('--y',`${(Math.random()-.5)*180}px`); $('particles').appendChild(p); setTimeout(()=>p.remove(),850); } }
function confetti(n=24){ const colors=['#ffd24f','#ff7fcb','#59d7ff','#49e7a3','#fff','#9e61ff']; for(let i=0;i<n;i++){ const c=document.createElement('span'); c.className='conf'; c.style.left=Math.random()*100+'%'; c.style.background=pick(colors); c.style.setProperty('--x',`${(Math.random()-.5)*160}px`); c.style.setProperty('--d',`${1.7+Math.random()*1.5}s`); $('confetti').appendChild(c); setTimeout(()=>c.remove(),3300); } }
function floatText(text, rect, color='#fff'){ const f=document.createElement('div'); f.className='floater'; f.textContent=text; f.style.left=(rect.left+rect.width/2-15)+'px'; f.style.top=(rect.top+rect.height/2)+'px'; f.style.color=color; $('floaters').appendChild(f); setTimeout(()=>f.remove(),1600); }
